"""add_github_fields_to_user

Revision ID: 1f70420ebc3d
Revises: 1b8e2927184c
Create Date: 2026-01-24 02:09:15.622239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f70420ebc3d'
down_revision: Union[str, None] = '1b8e2927184c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_access_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('github_username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'github_username')
    op.drop_column('users', 'github_access_token')
    # ### end Alembic commands ###
